all: build

build:
	@echo "Python does not have a build step"

release:
	@echo "Python does not have a release step"

run:
	python .

run-release: run

test:
	@echo "Python does not have a build int testing framework."
